"""Turn the find_dups.py result into a reviewable delete script.

Emits shell, never deletes. Two categories are held back on purpose:

  CD tracks   -- ".. (Track N).bin" files are named inside their game's .cue.
                 Ten Capcom PS1 discs share one byte-identical filler track;
                 deleting the "copies" breaks ten games to save 350 MB.
  arcade CHD  -- MAME parent/clone sets are looked up by filename, so two
                 identical chds can both be required.
  firmware    -- an emulator finds its bios by exact name in its own directory.
                 Batocera reads bios/scph39001.bin and PCSX2 reads
                 system/pcsx2/bios/scph39001.bin; the copy is the point.
  cue-named   -- anything a sibling .cue/.gdi/.m3u names by hand. Deleting a
                 track listed in a sheet breaks the game that references it.

Of each surviving group one copy is kept: the one whose name a human can read.
A bare "SLUS-21555 (1.02).iso" loses to "Lara Croft Tomb Raider - Anniversary
(USA).iso" even though the bytes are the same.
"""
import os, pickle, re, sys
from pathlib import Path

ID_ONLY = re.compile(r'^(?:[A-Z]{3,4}[-_]?\d{3,5})[\s._-]*(?:\(v?[\d.]+\))?$', re.I)

def is_cd_track(group):
    return any(re.search(r'\(Track \d+\)', Path(f).name) for f in group)

def is_chd(group):
    return any(Path(f).suffix.lower() == '.chd' for f in group)

def is_firmware(group):
    return any(re.search(r'(^|/)(bios|system|firmware)(/|$)', str(Path(f).parent), re.I)
               for f in group)

SHEETS = ('.cue', '.gdi', '.m3u', '.ccd', '.mds')

def is_cue_named(group):
    """True if any member is named inside a playlist/sheet next to it."""
    for f in group:
        d = Path(f).parent
        try:
            sheets = [x for x in d.iterdir() if x.suffix.lower() in SHEETS]
        except OSError:
            continue
        for sheet in sheets:
            try:
                if Path(f).name.lower() in sheet.read_text(errors='replace').lower():
                    return True
            except OSError:
                continue
    return False

def score(path):
    """Higher is a better name to keep."""
    stem = Path(path).stem
    return (0 if ID_ONLY.match(stem) else 1,      # a real title beats a disc id
            1 if re.search(r'\(USA\)|\(En', stem) else 0,   # region-tagged
            len(re.findall(r'[A-Za-z]{3,}', stem)),         # actual words
            -len(Path(path).parts))                         # shallower path

def main(dups_pkl=None, out_sh=None):
    if dups_pkl is None:
        try:
            dups_pkl, out_sh = sys.argv[1], sys.argv[2]
        except IndexError:
            print("usage: plan_dedup.py <duplicates.pkl> <delete.sh>",
                  file=sys.stderr)
            sys.exit(1)
    dups = pickle.load(open(dups_pkl, 'rb'))
    lines, freed = [], 0
    kept_back = {'CD track': 0, 'arcade CHD': 0, 'firmware': 0, 'named in a .cue': 0}
    for g in sorted(dups, key=lambda g: -os.stat(g[0]).st_size * (len(g) - 1)):
        if is_cd_track(g):
            kept_back['CD track'] += 1
            continue
        if is_chd(g):
            kept_back['arcade CHD'] += 1
            continue
        if is_firmware(g):
            kept_back['firmware'] += 1
            continue
        if is_cue_named(g):
            kept_back['named in a .cue'] += 1
            continue
        keep = max(g, key=score)
        size = os.stat(keep).st_size
        lines.append(f"\n# keep: {keep}")
        for f in sorted(g):
            if f == keep:
                continue
            freed += size
            lines.append(f"rm -v -- {sh(f)}")
    with open(out_sh, 'w') as fh:
        fh.write("#!/bin/bash\n# Review before running. Generated by plan_dedup.py.\n")
        fh.write("# Every rm below removes a file byte-identical to the 'keep' above it.\n")
        fh.write(f"# Would free {freed / 2**30:.1f} GB across {len(lines)} deletions.\n")
        fh.write("set -euo pipefail\n")
        fh.write("\n".join(lines) + "\n")
    os.chmod(out_sh, 0o755)
    print(f"wrote {out_sh}")
    print(f"  deletions : {sum(1 for l in lines if l.startswith('rm'))}")
    print(f"  frees     : {freed / 2**30:.1f} GB")
    print(f"  held back : {kept_back}")

def sh(p):
    return "'" + p.replace("'", "'\\''") + "'"

if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
